djangoapp/app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users import views as users_views


# TODO: production - replace path 'admin/' with env from secrets
# Define admin default url in djangohelm/values.yaml
urlpatterns = [
    path('', include('projects.urls')),
    path(settings.ADMIN_DEFAULT_URL, admin.site.urls),
    path('register/', users_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', users_views.user_profile, name='profile'),
    path("stripe/", include('djstripe.urls', namespace='djstripe')),
    path('order/', include('payments.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoapp/payments/urls.py
from django.urls import path

from payments.views import CheckoutView, OrderSummaryView, AddCouponView, RequestRefundView, \
    PaymentView, RetrievePaymentIntentView


# Needed for include(... namespace=...)
app_name = 'order'

urlpatterns = [
    path('', CheckoutView.as_view(), name='checkout'),
    path('summary/', OrderSummaryView.as_view(), name='order-summary'),
    # path('payment-old/<pay_option>/', PaymentView.as_view(), name='payment-old'),
    path('payment/<pay_option>/', PaymentView.as_view(), name='payment'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('refund/request/', RequestRefundView.as_view(), name='request-refund'),
    path('create-payment-intent/', RetrievePaymentIntentView.as_view(), name='get-payment-intent')
]

djangoapp/payments/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


"""
NOTE: forms.Form Classes essentially translate to html <input ... > elements or
      are used to directly replace values inside of them.
      - Used as input for GET request on the current view, where the data is 
        forwarded to another url via <form> element containing 
        action="{% url "..."}" method="POST"
      - Used as input for POST request on the current view directly replacing 
        arguments in an existing <input > element
"""

PAYMENT_CHOICES = [
    ('S', 'Stripe'),
    # ('P', 'PayPal')
]

PAYMENT_TYPES = [
    ('card', 'Card'),
    # ('ideal', 'Ideal'),
    # ('sepa', 'Sepa Debit')
]


class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Limmatplatz 1234'
    }))
    apartment_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '2nd Floor'
    }), required=False)
    country = CountryField(blank_label='(select country)').formfield(
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100'
    }))
    zip_code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    save_info = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)
    payment_method = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_TYPES)


class CouponForm(forms.Form):
    """
    CouponForm represents the following html input element (go to order_snippet.html)
    <input type="text" class="form-control" placeholder="Promo code" \
     aria-label="Recipient's username" aria-describedby="basic-addon2"
    """
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria - label': 'Recipient\'s username',
        'aria - describedby': 'basic-addon2'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    refund_email = forms.EmailField()

djangoapp/payments/views.py
import random
import string

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.http import response, JsonResponse
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.views import View
from djstripe import webhooks
from djstripe.models import Customer, PaymentIntent
from djstripe.sync import sync_subscriber

from payments.forms import CheckoutForm, CouponForm, RefundForm
from payments.models import Order, BillingAddress, RefundRequest

import logging
import stripe

"""
See all stripe webhook event types 
https://stripe.com/docs/api/events/types

"""

logger = logging.getLogger(__name__)


# TODO: Verify how this process can be integrated into path/to/site-packages/djstripe/models/checkout.Session
"""
STRIPE: We recommend creating a PaymentIntent as soon as the amount is known, 
        such as when the customer begins the checkout process.
        
        DO NOT USE STRIPE.JS CHECKOUT - the credit card form will do, bc PaymentIntents
        are set up already

CURRENT CHECKOUT LIFECYCLE (NEW: DJSTRIPE):

0. User is registered and logged in
   NEW:
     - create Customer (Django Signals)
1. User fills his cart in OrderSummaryView -> proceeds to checkout
   NEW:
     - create PaymentIntent
     - create new session ???
2. In CheckoutView user provides address and payment provider. He can optionally redeem a coupon -> proceeds to payment
3. User provides credit card credentials -> submit transaction
   NEW:
     - fetch PaymentIntent from 
4. Option for refund

"""


def log_error(err):
    return logger.error(f"Status is: {err.http_status},"
                        f"Type is: {err.error.type},"
                        f"Code is: {err.error.code}",
                        f"Param is: {err.error.param}")


stripe.api_key = settings.STRIPE_TEST_SECRET_KEY


@webhooks.handler("payment_intent")
def payment_intent_hook(event, **kwargs):
    # logger.info(f"[dj-stripe: hook]: PaymentIntent - {event.type}")
    if event.type == 'payment_intent.created':
        logger.info(f"[dj-stripe: hook]: {event.type} - create")
        # logger.info(f"[dj-stripe: hook]: {event.data}")
        payment_intent_stripe = event.data['object']
        PaymentIntent.sync_from_stripe_data(payment_intent_stripe)

    elif event.type == 'payment_intent.succeeded':
        logger.info(f"[dj-stripe: hook]: {event.type} - success")
        # logger.info(f"[dj-stripe: hook]: {event.data['object']}")
        try:
            customer_id = event.data['object']['customer']
            customer_qs = Customer.objects.filter(id=customer_id)
            order = Order.objects.get(customer=customer_qs[0], ordered=False)
            # STEP 3: Assign the payment to this order
            order_items = order.items.all()
            order_items.update(ordered=True)
            for item in order_items:
                item.save()
            # STEP 4: Show that order is filled
            order.ordered = True
            # order.payment = payment
            order.ref_code = order_reference()
            order.save()
        except AttributeError as e:
            logging.info(f"[dj-stripe: hook] Error: {e}")

    elif event.type == 'payment_intent.payment_failed':
        logger.info(f"[dj-stripe: hook]: {event.type} - failed")

    # payment_intent.amount_capturable_updated
    else:
        logger.info(f"[dj-stripe: hook]: {event.type} - updated")


# --------------- User Creation Signal for Customer object creation-----------------

# Every new user profile triggers the related customer object creation
def customer_receiver(sender, instance, created, *args, **kwargs):
    if created:
        customer = sync_subscriber(subscriber=instance)
        logger.info(f"[dj-stripe]: Customer created locally - {customer}")


# Utilize post_save signal when User is created
post_save.connect(customer_receiver, sender=User)

# ---------------------------------------------------------------------------------


def order_reference():
    return '-'.join([''.join(
        random.choices(string.ascii_uppercase + string.digits, k=4)) for _ in range(4)])


# @method_decorator(csrf_exempt, name='dispatch')
class RetrievePaymentIntentView(View):
    def post(self, *args, **kwargs):
        try:
            # Retrieve active payment intent
            customer_qs = Customer.objects.filter(subscriber=self.request.user)
            payment_intent_qs = PaymentIntent.objects.filter(customer=customer_qs[0]).exclude(
                status='succeeded').exclude(status='canceled')
            payment_intent = payment_intent_qs.get(customer=customer_qs[0])
            # EXPECTED OUTPUT
            out = {
                "clientSecret": payment_intent.client_secret,
                "publishableKey": settings.STRIPE_TEST_PUBLIC_KEY
            }
            # logging.info(f"[RetrievePaymentIntent] JSON output: {out}")
            return JsonResponse(out)
        except ObjectDoesNotExist:
            # logger.info(self.request.POST)
            messages.warning(self.request, "There are no OrderItems associated with this checkout.")
            return redirect('treesnqs-home')


# @method_decorator(csrf_exempt, name='dispatch')
class PaymentView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        customer_qs = Customer.objects.filter(subscriber=self.request.user)
        # payment_intent = PaymentIntent.objects.get(customer=customer_qs[0])
        order = Order.objects.get(customer=customer_qs[0], ordered=False)
        if order.billing_address:
            context = {
                'order': order,
                'DISPLAY_COUPON_FORM': False
            }
            return render(self.request, "payments/payment.html", context)
        else:
            messages.warning(self.request, "A billing address is required.")
            return redirect("order:checkout")


class CheckoutView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            customer_qs = Customer.objects.filter(subscriber=self.request.user)
            order = Order.objects.get(customer=customer_qs[0], ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'couponform': CouponForm(),
                'order': order,
                'DISPLAY_COUPON_FORM': True
            }
            return render(self.request, "payments/checkout-page.html", context)
        except ObjectDoesNotExist:
            return redirect("order:checkout")

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            customer_qs = Customer.objects.filter(subscriber=self.request.user)
            order = Order.objects.get(customer=customer_qs[0], ordered=False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                country = form.cleaned_data.get('country')
                zip_code = form.cleaned_data.get('zip_code')
                # TODO: Add save_info functionality
                # save_info = form.cleaned_data.get('save_info')
                billing_address = BillingAddress(
                    user=self.request.user,
                    street_address=street_address,
                    apartment_address=apartment_address,
                    countries=country,
                    zip_code=zip_code
                )
                billing_address.save()
                order.billing_address = billing_address
                order.save()
                # logger.info(form.cleaned_data)
                # logger.info("The form is valid.")
                payment_option = form.cleaned_data.get('payment_option')
                payment_method = form.cleaned_data.get('payment_method')
                if payment_option == 'S' and payment_method == 'card':
                    return redirect('order:payment', pay_option='stripe')
                # elif payment_option == 'P':
                #     return redirect('order:payment', pay_option='paypal')
                else:
                    messages.warning(self.request, "Invalid payment option.")
                    return render(self.request, 'payments/order-summary.html')
        except ObjectDoesNotExist:
            # logger.info(self.request.POST)
            messages.warning(self.request, "You don't have any Orders, yet.")
            return redirect('treesnqs-home')


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            customer_qs = Customer.objects.filter(subscriber=self.request.user)
            payment_intent_qs = PaymentIntent.objects.filter(customer=customer_qs[0]).exclude(
                status='canceled').exclude(status='succeeded')
            # logging.info(f"[OrderSummaryView] PaymentIntents QuerySet (Exclude 'succeeded,canceled': {payment_intent_qs}")
            order = Order.objects.get(customer=customer_qs[0], ordered=False)
            # STEP 1: Create new PaymentIntent or update amount of existing
            if payment_intent_qs.exists():
                amount_updated = order.get_total()
                payment_intent = payment_intent_qs.get(customer=customer_qs[0])
                if amount_updated != payment_intent.amount:
                    # logger.info(f"['dj-stripe'] captured payment_intent: {payment_intent}")
                    payment_intent.amount = amount_updated
                    payment_intent.update(sid=payment_intent_qs[0].id,
                                          amount=int(amount_updated*100))
                    payment_intent.save()
            elif not payment_intent_qs.exists() and len(order.items.all()) < 1:

djangoapp/payments/templates/payments/checkout-page.html
{% extends "projects/base_small.html" %}
{% load crispy_forms_tags %}

{% block content %}

<body>

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <hr>
      <h2>Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
            {% csrf_token %}
              <!--address-->
              <div class="md-form mb-5">
{#                <input type="text" id="address" class="form-control" placeholder="1234 Main St">#}
                {{ form.street_address }}
                <label for="address" class="">Address</label>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
{#                <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite">#}
                {{ form.apartment_address }}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  {{ form.country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip_code">Zip</label>
{#                  <input type="text" class="form-control" id="zip_code" placeholder="" required>#}
                    {{ form.zip_code }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

{#              <div class="custom-control custom-checkbox">#}
{#                <input type="checkbox" class="custom-control-input" id="same-address">#}
{#                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>#}
{#              </div>#}
              <div class="custom-control custom-checkbox">
                <input {% if form.save_info.value %} checked {% endif %} type="checkbox" class="custom-control-input" name="save-info" id="save-info">
{#                {{ form.save_info }}#}
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="row">
                  <div class="d-block my-3 col-md-3">
                    {% for value, name in form.fields.payment_option.choices %}
                    <div class="custom-control custom-radio">
                      {# In case of multiple payment options remove "checked" #}
                      <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" checked required>
                      <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
    {#                  {{ form.payment_option }}#}
                    </div>
    {#                <div class="custom-control custom-radio">#}
    {#                  <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>#}
    {#                  <label class="custom-control-label" for="paypal">Paypal</label>#}
    {#                </div>#}
                    {% endfor %}
                  </div>
                  <div class="d-block my-3 col-md-3">
                    {% for value, name in form.fields.payment_method.choices %}
                    <div class="custom-control custom-radio">
                      {# In case of multiple payment options remove "checked" #}
                      <input id="{{ name }}" name="payment_method" value="{{ value }}" type="radio" class="custom-control-input" checked required>
                      <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                    </div>
                    {% endfor %}
                  </div>
              </div>
              <hr class="mb-4">
              <button class="btn btn-outline-info btn-lg btn-block" type="stripeBtn">Continue to payment</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Order Snippet-->
        <div class="col-md-4 mb-4">
          {# couponform goes into order_snippet #}
          {% include "payments/order_snippet.html" %}
        </div>
        <!--Order Snippet-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

</body>

{% endblock content %}

djangoapp/payments/templates/payments/order_snippet.html
<!-- Heading -->
<h4 class="d-flex justify-content-between align-items-center mb-3">
<span class="text-muted">Your cart</span>
{#<span class="badge badge-info badge-pill">3</span>#}
</h4>

<!-- Cart -->
<ul class="list-group mb-3 z-depth-1">
{% for order_item in order.items.all %}
<li class="list-group-item d-flex justify-content-between lh-condensed">
  <div>
    <h6 class="my-0">{{ order_item.item.title }} x {{ order_item.quantity }}</h6>
    <small class="text-muted">{{ order_item.item.newproject_text }}</small>
  </div>
  <span class="text-muted">{{ order_item.get_final_price }}</span>
</li>
{% endfor %}
{% if order.coupon %}
<li class="list-group-item d-flex justify-content-between bg-light">
  <div class="text-success">
    <h6 class="my-0">Promo code</h6>
    <small>{{ order.coupon.code }}</small>
  </div>
  <span class="text-success">-{{ order.coupon.amount }}</span>
</li>
{% endif %}
<li class="list-group-item d-flex justify-content-between">
  <span>Total (CHF)</span>
  <strong>{{ order.get_total }}</strong>
</li>
</ul>
<!-- Cart -->

{% if DISPLAY_COUPON_FORM %}
<!-- Promo code -->
<form class="card p-2" action="{% url 'order:add-coupon' %}" method="POST">
  {% csrf_token %}
  <div class="input-group">
    {#  <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">#}
    {{ couponform.code }}
    <div class="input-group-append">
      <button class="btn btn-secondary btn-md waves-effect m-0" type="stripeBtn">Redeem</button>
    </div>
  </div>
</form>
<!-- Promo code -->
{% endif %}

djangoapp/payments/templates/payments/payment.html
{% extends "projects/base_small.html" %}
{% load static %}

{% block extra_head %}

    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <link  href="{% static 'css/normalize.css' %}" rel="stylesheet">
    <link  href="{% static 'css/global.css' %}" rel="stylesheet">

{% endblock extra_head %}
{% block content %}

<body>
    <main >
        <div class="container pt-5">
          <!--Section: Projects v.3-->
          <section class="text-center mb-4 pt-5">
          <!-- Heading -->
          <hr>
          <h2>Payment</h2>
          <!--Grid row-->
          <div class="row row fadeIn pt-5">
            <!--Grid column-->
            <div class="col-md-10 mb-4 offset-1">
                <script src="https://js.stripe.com/v3/"></script>
                <form id="payment-form" class="sr-payment-form">{% csrf_token %}
                  <div class="sr-combo-inputs-row">
                    <div class="sr-input sr-card-element" id="card-element"></div>
                  </div>
                  <div class="sr-field-error" id="card-errors" role="alert"></div>
                  <button id="submit">
                    <div class="spinner hidden" id="spinner"></div>
                    <span id="button-text">Submit Payment</span><span id="order-amount"></span>
                  </button>
                </form>
                <div class="sr-result hidden">
                  <p>Payment completed<br /></p>
                  <pre>
                      <h5></h5>
                  </pre>
                </div>
           </div>
            <div class="col-md-10 mb-4 offset-1">
              {% include "payments/order_snippet.html" %}
            </div>
          </div>
          </section>
        </div>
    </main>
</body>


<script type="text/javascript" nonce="P5atKcHUkp+o40UydJa9hw==">  // Create a Stripe client.
    // A reference to Stripe.js
    var stripe;

    var orderData = {
      items: [{ id: "photo-subscription" }],
      currency: "chf"
    };

    // Disable the button until we have Stripe set up on the page
    document.querySelector("button").disabled = true;

    function getCookie(name) {
        if (!document.cookie) {
        return null;
        }

    const xsrfCookies = document.cookie.split(';')
        .map(c => c.trim())
        .filter(c => c.startsWith(name + '='));

        if (xsrfCookies.length === 0) {
          return null;
        }

        return decodeURIComponent(xsrfCookies[0].split('=')[1]);
    }

    const csrfToken = getCookie('CSRF-TOKEN');

    // REPLACE WITH FETCH EXISTING PAYMENT INTENT
    fetch("{% url 'order:get-payment-intent' %}", {
      method: "POST",
      headers: {
        "X-CSRFToken": getCookie("csrftoken"),
        "Accept": "application/json",
        "Content-Type": "application/json"
      },
      body: JSON.stringify(orderData),
      credentials: "same-origin"
    })
      .then(function(result) {
        return result.json();
      })
      .then(function(data) {
        return setupElements(data);
      })
      .then(function({ stripe, card, clientSecret }) {
        document.querySelector("button").disabled = false;

        // Handle form submission.
        var form = document.getElementById("payment-form");
        form.addEventListener("submit", function(event) {
          event.preventDefault();
          // Initiate payment when the submit button is clicked
          pay(stripe, card, clientSecret);
        });
      });

    // Set up Stripe.js and Elements to use in checkout form
    var setupElements = function(data) {
      stripe = Stripe(data.publishableKey);
      var elements = stripe.elements();
      var style = {
        base: {
          color: "#32325d",
          fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
          fontSmoothing: "antialiased",
          fontSize: "16px",
          "::placeholder": {
            color: "#aab7c4"
          }
        },
        invalid: {
          color: "#fa755a",
          iconColor: "#fa755a"
        }
      };

      var card = elements.create("card", { style: style });
      card.mount("#card-element");

      return {
        stripe: stripe,
        card: card,
        clientSecret: data.clientSecret
      };
    };

    /*
     * Calls stripe.confirmCardPayment which creates a pop-up modal to
     * prompt the user to enter extra authentication details without leaving your page
     */
    var pay = function(stripe, card, clientSecret) {
      changeLoadingState(true);

      // Initiate the payment.
      // If authentication is required, confirmCardPayment will automatically display a modal
      stripe
        .confirmCardPayment(clientSecret, {
          payment_method: {
            card: card
          }
        })
        .then(function(result) {
          if (result.error) {
            // Show error to your customer
            showError(result.error.message);
          } else {
            // The payment has been processed!
            orderComplete(clientSecret);
          }
        });
    };

    /* ------- Post-payment helpers ------- */

    /* Shows a success / error message when the payment is complete */
    var orderComplete = function(clientSecret) {
      stripe.retrievePaymentIntent(clientSecret).then(function(result) {
        var paymentIntent = result.paymentIntent;
        {#var paymentIntentJson = JSON.stringify(paymentIntent, null, 2);#}

        document.querySelector(".sr-payment-form").classList.add("hidden");
        {#document.querySelector("pre").textContent = paymentIntentJson;#}
        {#document.querySelector("pre").textContent = "";#}

        document.querySelector(".sr-result").classList.remove("hidden");
        setTimeout(function() {
          document.querySelector(".sr-result").classList.add("expand");
        }, 200);

        changeLoadingState(false);
      });
    };

    var showError = function(errorMsgText) {
      changeLoadingState(false);
      var errorMsg = document.querySelector(".sr-field-error");
      errorMsg.textContent = errorMsgText;
      setTimeout(function() {
        errorMsg.textContent = "";
      }, 4000);
    };

    // Show a spinner on payment submission
    var changeLoadingState = function(isLoading) {
      if (isLoading) {
        document.querySelector("button").disabled = true;
        document.querySelector("#spinner").classList.remove("hidden");
        document.querySelector("#button-text").classList.add("hidden");
      } else {
        document.querySelector("button").disabled = false;
        document.querySelector("#spinner").classList.add("hidden");
        document.querySelector("#button-text").classList.remove("hidden");
      }
    };
</script>

{% endblock content %}

djangoapp/payments/templates/payments/request-refund.html
{% extends "projects/base_small.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <!--Main layout-->
  <main>
    <div class="container pt-5">
      <!--Section: Projects v.3-->
      <section class="text-left mb-4">
        <div class="row wow fadeIn col-md-10 pt-5">
          <div class="col-10 offset-2">
          <hr>
          <h2>Request Refund</h2>
          <form method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="'stripeBtn" class="btn btn-outline-info">stripeBtn</button>
          </form>
          </div>
        </div>

      <!--/.Projects Overview-->

      </section>
      <!--Section: Products v.3-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}